openapi: 3.0.0
info:
  contact:
    email: tomas.bocinec@siemens-healthineers.com
  description: Ambulance Waiting List management for Web-In-Cloud system
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  title: Waiting List Api
  version: 1.0.0
servers:
- description: Cluster Endpoint
  url: /api
tags:
- description: Ambulance Waiting List API
  name: ambulanceWaitingList
- description: Patient conditions and symptoms handled in the ambulance
  name: ambulanceConditions
paths:
  /waiting-list/{ambulanceId}/entries:
    get:
      description: By using ambulanceId you get list of entries in ambulance waiting
        list
      operationId: getWaitingListEntries
      parameters:
      - description: pass the id of the particular ambulance
        explode: false
        in: path
        name: ambulanceId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                response:
                  $ref: '#/components/examples/WaitingListEntriesExample'
              schema:
                items:
                  $ref: '#/components/schemas/WaitingListEntry'
                type: array
          description: value of the waiting list entries
        "404":
          description: Ambulance with such ID does not exist
      summary: Provides the ambulance waiting list
      tags:
      - ambulanceWaitingList
    post:
      description: Use this method to store new entry into the waiting list.
      operationId: createWaitingListEntry
      parameters:
      - description: pass the id of the particular ambulance
        explode: false
        in: path
        name: ambulanceId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              request-sample:
                $ref: '#/components/examples/WaitingListEntryExample'
            schema:
              $ref: '#/components/schemas/WaitingListEntry'
        description: Waiting list entry to store
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                updated-response:
                  $ref: '#/components/examples/WaitingListEntryExample'
              schema:
                $ref: '#/components/schemas/WaitingListEntry'
          description: Value of the waiting list entry with re-computed estimated
            time of ambulance entry
        "400":
          description: Missing mandatory properties of input object.
        "404":
          description: Ambulance with such ID does not exists
        "409":
          description: Entry with the specified id already exists
      summary: Saves new entry into waiting list
      tags:
      - ambulanceWaitingList
  /waiting-list/{ambulanceId}/entries/{entryId}:
    delete:
      description: Use this method to delete the specific entry from the waiting list.
      operationId: deleteWaitingListEntry
      parameters:
      - description: pass the id of the particular ambulance
        explode: false
        in: path
        name: ambulanceId
        required: true
        schema:
          type: string
        style: simple
      - description: pass the id of the particular entry in the waiting list
        explode: false
        in: path
        name: entryId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Item deleted
        "404":
          description: Ambulance or Entry with such ID does not exists
      summary: Deletes specific entry
      tags:
      - ambulanceWaitingList
    get:
      description: By using ambulanceId and entryId you can details of particular
        entry item ambulance.
      operationId: getWaitingListEntry
      parameters:
      - description: pass the id of the particular ambulance
        explode: false
        in: path
        name: ambulanceId
        required: true
        schema:
          type: string
        style: simple
      - description: pass the id of the particular entry in the waiting list
        explode: false
        in: path
        name: entryId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                response:
                  $ref: '#/components/examples/WaitingListEntryExample'
              schema:
                $ref: '#/components/schemas/WaitingListEntry'
          description: value of the waiting list entries
        "404":
          description: Ambulance or Entry with such ID does not exists
      summary: Provides details about waiting list entry
      tags:
      - ambulanceWaitingList
    put:
      description: Use this method to update content of the waiting list entry.
      operationId: updateWaitingListEntry
      parameters:
      - description: pass the id of the particular ambulance
        explode: false
        in: path
        name: ambulanceId
        required: true
        schema:
          type: string
        style: simple
      - description: pass the id of the particular entry in the waiting list
        explode: false
        in: path
        name: entryId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              request:
                $ref: '#/components/examples/WaitingListEntryExample'
            schema:
              $ref: '#/components/schemas/WaitingListEntry'
        description: Waiting list entry to update
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                response:
                  $ref: '#/components/examples/WaitingListEntryExample'
              schema:
                $ref: '#/components/schemas/WaitingListEntry'
          description: value of the waiting list entry with re-computed estimated
            time of ambulance entry
        "403":
          description: Value of the entryID and the data id is mismatching. Details
            are provided in the response body.
        "404":
          description: Ambulance or Entry with such ID does not exists
      summary: Updates specific entry
      tags:
      - ambulanceWaitingList
  /waiting-list/{ambulanceId}/condition:
    get:
      description: By using ambulanceId you get list of predefined conditions
      operationId: getConditions
      parameters:
      - description: pass the id of the particular ambulance
        explode: false
        in: path
        name: ambulanceId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                response:
                  $ref: '#/components/examples/ConditionsListExample'
              schema:
                items:
                  $ref: '#/components/schemas/Condition'
                type: array
          description: value of the predefined conditions
        "404":
          description: Ambulance with such ID does not exists
      summary: Provides the list of conditions associated with ambulance
      tags:
      - ambulanceConditions
components:
  examples:
    WaitingListEntryExample:
      description: |
        Entry represents a patient waiting in the ambulance prep room with
        defined symptoms
      summary: Ľudomír Zlostný waiting
      value:
        id: x321ab3
        name: Ľudomír Zlostný
        patientId: 74895-ludomir-zlostny
        waitingSince: 2038-12-24T10:05:00.000Z
        estimatedStart: 2038-12-24T10:35:00.000Z
        estimatedDurationMinutes: 15
        condition:
          value: Nevoľnosť
          code: nausea
          reference: https://zdravoteka.sk/priznaky/nevolnost/
    ConditionExample:
      description: list of few symptoms that can be chosen by patients
      summary: Conditions and symptoms
      value:
        valuee: Teploty
        code: subfebrilia
        reference: https://zdravoteka.sk/priznaky/zvysena-telesna-teplota/
    WaitingListEntriesExample:
      description: |
        Example waiting list containing 2 patients
      summary: List of waiting patients
      value:
      - id: x321ab3
        name: Jožko Púčik
        patientId: 460527-jozef-pucik
        waitingSince: 2038-12-24T10:05:00.000Z
        estimatedStart: 2038-12-24T10:35:00.000Z
        estimatedDurationMinutes: 15
        condition:
          value: Teploty
          code: subfebrilia
          reference: https://zdravoteka.sk/priznaky/zvysena-telesna-teplota/
      - id: x321ab4
        name: Ferdinand Trety
        patientId: 780907-ferdinand-tre
        waitingSince: 2038-12-24T10:25:00.000Z
        estimatedStart: 2038-12-24T10:50:00.000Z
        estimatedDurationMinutes: 25
        condition:
          value: Nevoľnosť
          code: nausea
          reference: https://zdravoteka.sk/priznaky/nevolnost/
    ConditionsListExample:
      description: |
        Example list of possible conditions, symptoms, and visit reasons
      summary: Sample of GP ambulance conditions
      value:
      - value: Teploty
        code: subfebrilia
        reference: https://zdravoteka.sk/priznaky/zvysena-telesna-teplota/
        typicalDurationMinutes: 20
      - value: Nevoľnosť
        code: nausea
        reference: https://zdravoteka.sk/priznaky/nevolnost/
        typicalDurationMinutes: 45
      - value: Kontrola
        code: followup
        typicalDurationMinutes: 15
      - value: Administratívny úkon
        code: administration
        typicalDurationMinutes: 10
      - value: Odber krvi
        code: blood-test
        typicalDurationMinutes: 10
  schemas:
    WaitingListEntry:
      example:
        $ref: '#/components/examples/WaitingListEntryExample'
      properties:
        id:
          description: Unique id of the entry in this waiting list
          example: x321ab3
          type: string
        name:
          description: Name of patient in waiting list
          example: Jožko Púčik
          type: string
        patientId:
          description: Unique identifier of the patient known to Web-In-Cloud system
          example: 460527-jozef-pucik
          type: string
        waitingSince:
          description: Timestamp since when the patient entered the waiting list
          example: 2038-12-24T10:05:00Z
          format: date-time
          type: string
        estimatedStart:
          description: Estimated time of entering ambulance. Ignored on post.
          example: 2038-12-24T10:35:00Z
          format: date-time
          type: string
        estimatedDurationMinutes:
          description: Estimated duration of ambulance visit. If not provided then
            it will be computed based on condition and ambulance settings
          example: 15
          format: int32
          type: integer
        condition:
          $ref: '#/components/schemas/Condition'
      required:
      - estimatedDurationMinutes
      - id
      - patientId
      - waitingSince
      type: object
    Condition:
      description: "Describes disease, symptoms, or other reasons of patient   visit"
      example:
        $ref: '#/components/examples/ConditionExample'
      properties:
        value:
          example: Teploty
          type: string
        code:
          example: subfebrilia
          type: string
        reference:
          description: Link to encyclopedical explanation of the patient's condition
          example: https://zdravoteka.sk/priznaky/zvysena-telesna-teplota/
          format: url
          type: string
        typicalDurationMinutes:
          example: 20
          format: int32
          type: integer
      required:
      - value
